CREATE TABLE PHIEUXUATHANG(
    MAPHIEUXUAT varchar2(20) not null,
    NGAYTAO date,
    NGUOITAO varchar2(20)
);
ALTER TABLE PHIEUXUATHANG
    ADD CONSTRAINT MPX_PK PRIMARY KEY (MAPHIEUXUAT);
ALTER TABLE PHIEUXUATHANG
    ADD CONSTRAINT PXH_FK FOREIGN KEY (NGUOITAO) REFERENCES NHANVIEN (MaNV);