CREATE TABLE CHITIETXUATHANG(
    Maxuathang varchar2(20) not null,
    Sophieuxuat varchar2(20),
    Soluong int
);
ALTER TABLE CHITIETXUATHANG
    ADD CONSTRAINT CTXH_PK PRIMARY KEY (Maxuathang);
ALTER TABLE CHITIETXUATHANG
    ADD CONSTRAINT CTXH_FK FOREIGN KEY (Sophieuxuat) REFERENCES PHIEUXUATHANG (Sophieu);