CREATE TABLE KHUYENMAI(
    MAKHUYENMAI  varchar2(25),
    NGAYBATDAU date,
    NGAYKETTHUC date,
    NGAYHD date
);
ALTER TABLE KHUYENMAI
    ADD CONSTRAINT MKM_PK PRIMARY KEY (MAKHUYENMAI);
ALTER TABLE KHUYENMAI
    ADD CONSTRAINT KM_FK FOREIGN KEY (NGAYHD) REFERENCES HOADON (NGAYHD);
--ngay khuyen mai phai nam trong ngay hoa don