CREATE TABLE CTHD(
    SoHD varchar2(20) not null,
    MaSP varchar(20) not null,
    Soluong int
);
ALTER TABLE CTHD
    ADD CONSTRAINT CTHD_FK01 FOREIGN KEY (SoHD) REFERENCES HOADON (SoHD);
ALTER TABLE CTHD
    ADD CONSTRAINT CTHD_FK02 FOREIGN KEY (MaSP) REFERENCES HANGHOA (Mahang);