CREATE TABLE PHIEUNHAPHANG(
    MAPHIEUNHAP varchar2(20) not null,
    NGAYTAO date,
    SOLUONG int,
    NGUOITAO varchar2(20),
    TONGTIENNHAPHANG varchar2(20),
    MANV varchar2(25)
);
ALTER TABLE PHIEUNHAPHANG
    ADD CONSTRAINT MPN_PK PRIMARY KEY (MAPHIEUNHAP);
ALTER TABLE PHIEUNHAPHANG
    ADD CONSTRAINT PNH_FK FOREIGN KEY (NGUOITAO) REFERENCES NHANVIEN (MaNV);